---
- name: postgresql Playbook
  hosts: all
  become: true
  vars_files:
    - vault.yml  # encrypted file containing pg_password variable

  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name:
          - postgresql
          - postgresql-server
          - postgresql-contrib
          - postgresql-libs
          - python3-psycopg2
        state: present

    - name: Check if PostgreSQL is initialized
      ansible.builtin.stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
      register: postgres_data

    - name: Initialize PostgreSQL
      ansible.builtin.shell: "postgresql-setup initdb"
      when: not postgres_data.stat.exists

    - name: Start and enable service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Get postgres user home directory
      ansible.builtin.command: "bash -c 'echo $HOME'"
      become_user: postgres
      register: postgres_home

    - name: Create .pgpass file for postgres user securely
      ansible.builtin.copy:
        dest: "{{ postgres_home.stdout }}/.pgpass"  # path to .pgpass in postgres home
        content: "*:*:*:postgres:{{ pg_password }}"  # format: hostname:port:db:user:password
        owner: postgres
        group: postgres
        mode: '0600'  # file permission must be 0600 for security reason
      no_log: true  # hide sensitive content from logs